[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.build]
cmds = [
  "cd backend",
  "npm ci",
  "npx prisma generate", 
  "npm run build"
]

[phases.start]
cmd = "cd backend && npx prisma migrate deploy && npm start"

[variables]
NODE_ENV = "production"